[[headers]]
for = "/fonts/*.woff2"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "application/font-woff2"
[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "no-referrer"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
